# This code was generated by @basketry/rails@{{version}}
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.
#
# To make changes to the contents of this file:
# 1. Edit source/path.ext
# 2. Run the Basketry CLI
#
# About Basketry: https://github.com/basketry/basketry/wiki
# About @basketry/rails: https://github.com/basketry/rails#readme

scope module: 'basketry_example' do
  scope path: 'v1' do
    # Gizmos
    get 'gizmos', to: 'gizmos#get_gizmos'
    post 'gizmos', to: 'gizmos#create_gizmo'
    put 'gizmos', to: 'gizmos#update_gizmo'

    # Widgets
    get 'widgets/:id/foo', to: 'widgets#get_widget_foo'
    delete 'widgets/:id/foo', to: 'widgets#delete_widget_foo'
    get 'widgets', to: 'widgets#get_widgets'
    post 'widgets', to: 'widgets#create_widget'
    put 'widgets', to: 'widgets#put_widget'

    # Exhaustive
    get 'exhaustive/:path-string/:path-enum/:path-number/:path-integer/:path-boolean/:path-string-array/:path-enum-array/:path-number-array/:path-integer-array/:path-boolean-array', to: 'exhaustives#exhaustive_params'
    get 'exhaustive', to: 'exhaustives#exhaustive_formats'

    # Auth permutations
    get 'authPermutations', to: 'auth_permutations#all_auth_schemes'
    put 'authPermutations', to: 'auth_permutations#combo_auth_schemes'
  end
end
