# This code was generated by @basketry/rails@{{version}}
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.
#
# To make changes to the contents of this file:
# 1. Edit source/path.ext
# 2. Run the Basketry CLI
#
# About Basketry: https://github.com/basketry/basketry/wiki
# About @basketry/rails: https://github.com/basketry/rails#readme

module BasketryExample
  class AuthPermutationsController < ActionController::Base
    include ControllerHelpers

    def all_auth_schemes
      response = auth_permutation_service.all_auth_schemes(
      )

      render status: get_status_code(response)
    end

    def combo_auth_schemes
      response = auth_permutation_service.combo_auth_schemes(
      )

      render status: get_status_code(response)
    end
  end
end
