# This code was generated by @basketry/rails@{{version}}
#
# Changes to this file may cause incorrect behavior and will be lost if
# the code is regenerated.
#
# To make changes to the contents of this file:
# 1. Edit source/path.ext
# 2. Run the Basketry CLI
#
# About Basketry: https://github.com/basketry/basketry/wiki
# About @basketry/rails: https://github.com/basketry/rails#readme

module BasketryExample
  class ExhaustivesController < ApplicationController
    include BasketryExample::ControllerHelpers

    def exhaustive_formats
      response = services.exhaustive_service.exhaustive_formats(
        string_no_format: params['string-no-format'],
        string_date: cast_date(params['string-date']),
        string_date_time: cast_date_time(params['string-date-time']),
        integer_no_format: cast_integer(params['integer-no-format']),
        integer_int32: cast_integer(params['integer-int32']),
        integer_int64: cast_long(params['integer-int64']),
        number_no_format: cast_number(params['number-no-format']),
        number_float: cast_float(params['number-float']),
        number_double: cast_double(params['number-double'])
      )

      render status: status_code(response.errors) || 204
    end

    def exhaustive_params
      response = services.exhaustive_service.exhaustive_params(
        query_string: params['query-string'],
        query_enum: params['query-enum'],
        query_number: cast_number(params['query-number']),
        query_integer: cast_integer(params['query-integer']),
        query_boolean: cast_boolean(params['query-boolean']),
        query_string_array: params['query-string-array']&.split(','),
        query_enum_array: params['query-enum-array'],
        query_number_array: cast_number_array(params['query-number-array']&.split(',')),
        query_integer_array: cast_integer_array(params['query-integer-array']&.split(',')),
        query_boolean_array: cast_boolean_array(params['query-boolean-array']&.split(',')),
        path_string: params['path-string'],
        path_enum: params['path-enum'],
        path_number: cast_number(params['path-number']),
        path_integer: cast_integer(params['path-integer']),
        path_boolean: cast_boolean(params['path-boolean']),
        path_string_array: params['path-string-array']&.split(','),
        path_enum_array: params['path-enum-array'],
        path_number_array: cast_number_array(params['path-number-array']&.split(' ')),
        path_integer_array: cast_integer_array(params['path-integer-array']&.split('	')),
        path_boolean_array: cast_boolean_array(params['path-boolean-array']&.split(',')),
        header_string: params['header-string'],
        header_enum: params['header-enum'],
        header_number: cast_number(params['header-number']),
        header_integer: cast_integer(params['header-integer']),
        header_boolean: cast_boolean(params['header-boolean']),
        header_string_array: params['header-string-array']&.split(','),
        header_enum_array: params['header-enum-array'],
        header_number_array: cast_number_array(params['header-number-array']&.split('|')),
        header_integer_array: cast_integer_array(params['header-integer-array']&.split(' ')),
        header_boolean_array: cast_boolean_array(params['header-boolean-array']&.split('	')),
        body: map_dto_to_exhaustive_params_body(JSON.parse(request.body.read))
      )

      render status: status_code(response.errors) || 204
    end
  end
end
